# Path to the original GEX output
path.hdf5 <- "path/to/filtered_feature_bc_matrix.h5"

# The number of genes narrowed
how.many.genes <- 2000

# Path to toy gex barcodes generated by multiome_toy.sh
path.to.gexbarcode <- "toygex_barcodes.txt"



# Path to bash script
multiome.toy.bash <- "multiome_toy.sh"

# Path to peaks tsv
path.to.peak <- "toy_peaks_peaks.tsv"


# Path to toy matrix output (rds file)
path.to.toymatrix <- "toy_matrix.rds"



