tenx.input <- "tenx_input"
tenx.output <- "../tenx_multiome_toy"


# Path to the original GEX output
path.hdf5 <- file.path(tenx.input, "filtered_bc_matrix.h5")

# The number of genes narrowed
how.many.genes <- 2000

# Path to toy gex barcodes generated by multiome_toy.sh
path.to.gexbarcode <- file.path(tenx.output, "toygex_barcodes.txt")

# Path to barcode
path.to.bc <- file.path(tenx.output, "toy_barcode.csv")


# Path to peaks tsv
path.to.peak <- file.path(tenx.output, "toy_peaks_peaks.tsv")


# Path to toy matrix output (rds file)
path.to.toymatrix <- file.path(tenx.output, "toy_matrix.rds")



