---
title: "Building Annotation from User Provided GTF"
output:
    html_document:
            toc: true
            toc_float: true
            code_folding: hide
---


This workflow is designed to build a `GRanges` object from a user-provided `GTF` file.


```{r global_options, include=FALSE}
knitr::opts_chunk$set(
    warning=FALSE,
    message=FALSE
    )
```

```{r load_packages}
library(readr)
library(knitr)
library(Signac)
library(Seurat)
library(GenomicRanges)
library(future)

set.seed(127)
```


```{r parallelize, include=FALSE}

# Assign the number of cores for parallelization
ncpus <- future::availableCores()

# Adjust max memory allowed
options(future.globals.maxSize=40000 * 1024^2,
        mc.cores=ncpus)

# Parallelize the run
plan("multicore", workers=ncpus)
```

# Loading path variables

```{r rule_variables}

print('yaml params:')
print(params)

annotation.file <- params[['anno_file']]
genome <- params[['genome']]

```

# Build annotation from generic GTF


```{r annotation_from_generic_GTF, cache=TRUE}
# use cellranger supplied genome to determine whether TSSEnrichment takes any generic annotation file
# as long as in GRanges format and seqlevels match feature coordinates

gtf.ranges <- rtracklayer::import(con = annotation.file)

# common filtering steps for EnsDb and standard GTF objects:
# add generic "gene_biotype" column, Ensdb.Species uses gene_biotype other repos (i.e. Ensembl) use "gene_type"
# Also avoids the following:
# Error in GetTSSPositions(ranges = annotations) : Gene annotation does not contain gene_biotype information
if ( any(colnames(mcols(gtf.ranges)) %in% "gene_type") ) {
  gtf.ranges$gene_biotype <- gtf.ranges$gene_type
}

```

# Pseudogene types

```{r annotation_from_GTF_pseudogenes}

# Optional
# Use all gene/transcript types except pseudogenes:
pseudogene.types <- unique(gtf.ranges$gene_biotype)[grep(".*pseudogene.*", unique(gtf.ranges$gene_biotype) )]

# Remove unwanted genes
remove.genes <- c("TEC", pseudogene.types, "Mt_.*")

print("Following gene types are removed:")
for (g in remove.genes) {
    print(g)
}

remove.index <- grepl(paste(remove.genes, collapse="|"), gtf.ranges$gene_biotype)
gtf.ranges <- gtf.ranges[ !remove.index ]

# seqlevelsStyle(gtf.ranges) <- 'UCSC'

# Ootional
# remove non-standard chromosomes and mitochondrial (has no chromatin)
# Does not affect TSSEnrichment() but should be done for downstream analyses.


if (genome == 'mm10') {
    genomeStyles.species = 'Mus_musculus'
} else if (genome == 'hg38') {
    genomeStyles.species = 'Homo_sapiens'
}

# genomeStyles.species = 'Mus musculus'
gtf.ranges <- keepStandardChromosomes(
    gtf.ranges,
    species = genomeStyles.species,
    pruning.mode = 'coarse')
gtf.ranges <- gtf.ranges[!seqnames(gtf.ranges) == "chrM"]
```


# Seqlavels


```{r annotation_from_GTF_seqlevels}

print("seqlevels in the current GRanges obj:")
print(seqlevels(gtf.ranges))

print("seqnames in the current GRanges obj:")
print(unique(seqnames(gtf.ranges)))


gtf.genes <- gtf.ranges[gtf.ranges$type == "gene"]
annotation <- gtf.genes

genome(annotation) <- genome

```

#  Annotation summary


```{r annotation_from_GTF_summary}
# Explore the annotation object
# Note: make sure you have gene_biotype column.
print(paste("Annotation summary:", summary(annotation)))

print(head(data.frame(annotation), 3))
```

# Save

```{r save_annotation_output}
saveRDS(annotation, params[['anno_atac']])
print(paste('Annotation GRanges obj saved as', params[['anno_atac']]))
```


# Session Info

```{r session_info}

sessionInfo()
```

