---
title: "chooseR"
output:
    html_document:
        toc_float: true
        toc: true
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,
                      message=FALSE)
```

```{r packages_and_functions, include=FALSE}
library(tidyverse)
library(data.table)
library(ggplot2)
library(Signac)
library(Seurat)
library(knitr)
library(Matrix)
library(cluster)
library(purrr)
# library(future)
# library(parallel)

set.seed(1327)  # added to remove unwanted randomness

# Set correct paths
source("chooser/R/pipeline.R")
```

```{r config}
config_path <- params[['config']]
res <- as.numeric(params[["res"]])

# Number of chooseR iteration
# nIter <- 10	# Testing only
nIter <- 20
```


# Load Seurat object

**Input data** is an RDS file storing a **seurat object** preprocessed with normalization and dimensionality
reduction.


```{r load_data}
config <- yaml::read_yaml(file = config_path)

# Read a QC-ed seuat object
obj <- readRDS(params[["seurat_in"]])

# Explore the output
obj
```

# Set variables

```{r set_variables}

# Define the number of PCs to use, and which assay and reduction to use.
# We recommend testing a broad range of resolutions
# For more on picking the correct number of PCs, see:
# https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html
# npcs <- obj@commands$RunPCA.SCT@params$npcs
# assay <- "SCT"
# reduction <- "pca"

# Identify your target configured
target <- params[["seurat_out"]]

print(paste("Target group:", target))

groups <- config[['chooser']][['groups']]
idx <- which(names(groups) %in% target)

# Break if your target is not present in the input Seurat obj
if (length(idx) == 0) {
    stop("Group is not present in config's normalize groups list.")
} else if (length(idx) > 1) {
    stop("You are trying to normalize group/assay multiple times. Please fix.")
}

group_name <- names(groups)[idx]
print(paste('Current group:', group_name))

# determined by ElbowPlots from normalize/integrate rules
npcs <- groups[[idx]][['npcs']]

print(paste('Number of dimensions:', npcs))

# Identify dimensionality reduction performed in the previous step for the input obj
dim_reductions <- c("pca", "lsi")
reduction <- names(obj@reductions)
reduction_idx <- sapply(dim_reductions, function(r) str_detect(reduction, r))

# Break if the number of dimensionality reduction is 0 or more than 1 unintegrated dimensionality reductions
# found
if (sum(reduction_idx) > 1) {
    if (any(str_detect(reduction, "integrated"))) {
        reduction <- reduction[str_detect(reduction, "integrated")]
    }
    else {
        stop("More than one dimensionality reduction found!")
    }
} else if (sum(reduction_idx) == 0) {
    stop("Dimensionality reduction missing!")
}

# Identify assay in the current obj
assay <- obj[[reduction]]@assay.used

# Create a directory for output plots
# create sample subdir - May be multiple chooseR scripts running at once.
results_path <- params[['results_path']]

# Create output directory if it's missing
if (! dir.exists(results_path)) { dir.create(results_path) }

print(paste("Output directory created:", results_path))
```

# Run chooseR

The [ChooseR](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-03957-4) analyzes the 
optimal resolution for single cell clustering based on silhouette scores by iteratively calculating on
sampled cells.

```{r chooser}

# Run pipeline
print(paste0("Clustering ", res, "..."))
print("Finding ground truth...")

# "Truths" will be stored at glue::glue("{reduction}.{assay}_res.{res}")
obj <- find_clusters(
    obj,
    npcs=npcs,
    reduction = reduction,
    assay = assay,
    resolution = res)


# Now perform iterative, sub-sampled clusters (returns a data frame)
results <- multiple_cluster(
    obj,
    n = nIter,
    npcs = npcs,
    res = res,
    reduction = reduction,
    assay = assay)



# Explore the clusters (first 5 rows and columns)
print(paste("Number of cells sampled:", nrow(results)))
print(paste("Times sampling performed:", ncol(results)))

# Extract sampled barcodes
sampled.cells <- results$cell

# Now calculate the co-clustering frequencies
message(paste0("Tallying ", res, "..."))

# This is the more time efficient vectorisation
# However, it exhausts vector memory for (nearly) all datasets
# matches <- purrr::map(columns, find_matches, df = results)
# matches <- purrr::reduce(matches, `+`)

# CR change:
results <- results[,-1]
columns <- colnames(results)

mtchs <- matrix(0, nrow = dim(results)[1], ncol = dim(results)[1])

i <- 1 # Counter

for (col in columns) {
message(paste0("\tRound ", i, "..."))
mtchs <- Reduce("+", list(
  mtchs,
  find_matches(col, df = results)
))
i <- i + 1
}

message(paste0("Scoring ", res, "..."))
# Original code: # returns class "tibble", all cols type "double"
# matches <- dplyr::mutate_all(
# dplyr::as_tibble(matches),
# function(x) dplyr::if_else(Re(x) > 0, percent_match(x), 0)
# )
# Converted matrix to data frame:
mtchs <- apply(as.data.frame(mtchs),
               2,
               function(x) dplyr::if_else(Re(x) > 0, percent_match(x), 0))

# Sometimes next line causes error for some reason
# mtchs[1:5, 1:5]
print(paste0("Scores row x column: ", dim(mtchs)[1], ", ", dim(mtchs)[2]))

# Now calculate silhouette scores
message(paste0("Silhouette ", res, "..."))


# Subset the seurat obj by sampled cells
if (length(sampled.cells) > 0) {
    sampled.obj <- obj[, sampled.cells]
} else {
    sampled.obj <- obj
}

# Extract clusters from the sampled seurat
clusters <- unlist(sampled.obj[[glue::glue("{reduction}.{assay}_res.{res}")]])

# Compute silhouette width
# NOTE: cluster::silhouette() requires
# either dist (distance matrix) or dmatrix (dissimilarity matrix)
sil <- tryCatch(
    expr= { 
        cluster::silhouette(
            x =as.integer(clusters),   # integer vector of the initial cluster
            dmatrix=as.matrix(cluster::daisy(mtchs)))  # distance matrix
        },
    error=function(e) { return(NULL) }
)


# Save the silhouette object
saveRDS(sil, paste0(results_path, "/silhouette_", res, ".rds"))

# Finally, calculate grouped metrics
message(paste0("Grouping ", res, "..."))


# Compute group scores by passing a data table and clusters
grp <- tryCatch(
    expr={ group_scores(as.data.table(mtchs), clusters) },
    error=function(e) { NULL }
    )


# Ocassionally the sil is returned NA by the function cluster::silhouette() when
# - the size of input dataset is small and/or
# - the resolution is too high
# tryCatch() is applied in order to avoid possible errors under this condition
sil <- tryCatch(

    # Code to run (will return a data frame containing cluster, avg_sil, and res)
    expr = { group_sil(sil, res) },

    # If sil is returned NA by cluster::silhouette(),
    # an empty data frame is created
    error = function(e) {
        message("\n\n")
        message("Computing sil has failed due to missing sil!")
        message("This returns an empty data frame.")
        return(data.frame())
    }
    )
```

## Save objects


```{r save}

grp_path <- paste0(results_path, "/frequency_grouped_", res, ".rds")
sil_path <- paste0(results_path, "/silhouette_grouped_", res, ".rds")
obj_path <- paste0(results_path, "/seurat_obj_", res, ".rds")

print("Output files saved to the following paths")
print(paste("- Frequency groups:", grp_path))
print(paste("- Silhouette groups:", sil_path))
print(paste("- Sampled seurat obj:", obj_path))

saveRDS(grp, grp_path)   # short (seconds)
saveRDS(sil, sil_path)  # short (seconds)
saveRDS(sampled.obj, obj_path, compress=FALSE)   # takes nearly 20min
```

## Session info

```{r session_info}
sessionInfo()
```


