---
title: "Finding Markers"
output:
    html_document:
            toc: true
            toc_float: true
            code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    warning=FALSE,
    message=FALSE
    )

```

```{r packages_and_functions, include=FALSE}
library(tidyverse)
library(parallel)
library(Signac)
library(Seurat)
library(knitr)
library(future)
set.seed(1234)

source('common.R')
```


```{r parallelize, include=FALSE}

# Assign the number of cores for parallelization
ncpus <- future::availableCores()

# Adjust max memory allowed
options(future.globals.maxSize=40000 * 1024^2,
        mc.cores=ncpus)

# Parallelize the run
plan("multicore", workers=ncpus)

```

# Read in data

Read in Seurat object.

```{r input}

# Read configuration
config_path <- params[['config']]
config <- yaml::read_yaml(file = config_path)

# Import Seurat object
seurat <- readRDS(params[['seurat_in']])
print('Input seurat object:')
print(seurat)

```


# Find markers

```{r get_analysis_group_and_threshold}

# Retrieve group info
group <- config[['diff_analysis']][['groups']][[ params[["seurat"]] ]]
group_name <- params[["seurat"]]

print(paste('Current group:', group_name))

# Retrieve FDR threshold info
alpha <- group[['alpha']]
alpha <- ifelse(is.numeric(alpha), alpha, as.numeric(alpha))
```


```{r choose_clustering_column}

# Assign column name used for clustering
cluster_idents <- group[['cluster_idents']]

# Determine the clustering column to seurat_clusters if it's missing
ident_name <- ifelse(
    is.null(cluster_idents),
    "seurat_clusters",
    cluster_idents)


# Find columns storing WNN clustering
# NOTE: should only have one resolution column that is copied to "seurat_clusters"
#       except for weighted nearest neighbor objects
pattern <- ".*wsnn_res\\.[0-9]+.*"
idx <- grep(pattern = pattern, x = names(seurat@meta.data))

# Update the idx if WNN is not present
if (length(idx) > 0) {
    print("Weighted snn idents identical to cluster_idents?")
} else {
    pattern <- ".*snn_res\\.[0-9]+.*"
    idx <- grep(pattern = pattern, x = names(seurat@meta.data))
    print("Shared nn idents identical to cluster_idents?")
}

```

```{r marker_genes}

# Ex: "Gene.Expression" with "data" slot, "SCT" with "scale.data"
# Ex: "Peaks" with "data", "GeneActivity" with "data"
if (length(ident_name) > 0) {

    print(paste("Finding markers for:", ident_name))
    
    Idents(object = seurat) <- ident_name
    
    slot_use <- ifelse(is.null(group[['slot']]), "data", group[['slot']])
    
    # Set default values if they are null in config.yaml
    if (is.null(group[['assay']])) {

        # Determine the name of reduced dimension and assay for plotting
        targets <- c("pca", "lsi")
        idx <- grep(paste(targets,collapse="|"), names(seurat@reductions))
        red_use <- names(seurat@reductions)[idx]
        red_use <- if (any(sapply(red_use, function(r) str_detect(r, "integrated")))) {
            red_use[str_detect(red_use, "integrated")]
        } 
        assay_use <- seurat@reductions[[red_use]]@assay.used

    } else {
        assay_use <- group[['assay']]
        assay_present <- any(names(seurat@assays) %in% assay_use)
    
        # Break if user-configured assay is not available in the current Seurat object
        if (assay_present) {
            matrix_use <- GetAssayData(object = seurat,
                                      assay = assay_use,
                                      slot = slot_use)
            if (nrow(matrix_use) == 0 && ncol(matrix_use) == 0) {
                stop("Assay and slot defined in config file is empty!")
            }
        }
    }

    # Assign parameters for marker computation
    min_pct <- ifelse(is.null(group[['min_pct']]), 0.1, group[['min_pct']])
    test_use <- ifelse(is.null(group[['test_use']]), 'wilcox', group[['test_use']])

    print(paste("Minimum fraction of cells for testing a gene:", min_pct))
    print(paste("Testing method:", test_use))

    # fix later:
    # Warning: 'latent.vars' is only used for the following tests: negbinom, poisson, MAST, LR
    markers_df <- FindAllMarkers(
        object = seurat,
        assay = assay_use,
        slot = slot_use,
        min.pct = min_pct,
        verbose = FALSE,
        test.use = test_use,
        latent.vars = group[['latent_vars']]
    )
 
    # Add columns for extra information
    markers_df$group <- rep(ident_name, nrow(markers_df))
    markers_df$assay <- rep(assay_use, nrow(markers_df))
    markers_df$slot <- rep(slot_use, nrow(markers_df))
}

# Filter out non DEGs from the data frame
print(paste("FDR threshold:", alpha))
markers_df <- markers_df[markers_df$p_val_adj <= alpha,] %>%
    # Reorder columns
    rownames_to_column("Gene") %>%
    dplyr::select(-gene)

```


# Save Seurat object

```{r save, results='asis'}

path_out <- params[['markers_out']]
cat("- DE table: [", path_out, "](", path_out, ")")

write.table(
    x = markers_df,
    file = params[['markers_out']],
    sep = "\t",
    col.names = TRUE,
    row.names = FALSE,
    quote = FALSE)

```


# Session Info

```{r session_info}
sessionInfo()

```


