import pandas as pd
import numpy as np
import os
from itertools import compress

##### for interactive debugging
# import yaml
# with open("config/multiome-config/config.yaml", 'r') as stream:
#     config = yaml.safe_load(stream)


##### load config and sample sheets #####
configfile: "config/multiome-config/config.yaml"


# configuration = "config/config.yaml"
# workflow.configfiles generates a list
# in this case, starts with ["config/config.yaml"]
# any files in snakemake --configfile are added by "list.insert(0, x)"
# so snakemake --configfile test.yaml test1.yaml will return:
# ["test1.yaml", "test.yaml", "config/config.yaml"]
configuration = workflow.configfiles[0]


# print(workflow.configfiles)   # uncomment for testing
# print(configuration)      # uncomment for testing

# using Rmarkdown outputs as guide/report
# report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

# Import sampletable
samples = pd.read_table(config["samples"]).set_index(["sample", "replicate"], drop=False)
samples.index.names = ["sample", "replicate"]
samples.index = samples.index.set_levels(
    [i.astype(str) for i in samples.index.levels]
)  # enforce str in index

# Set chooser variables
resolutions = config['chooser']['resolutions']
chooser_sil = config['chooser']['silhouette']
user_resolution = config['cluster']['resolution']


####### helpers ###########

def is_activated(xpath):
    """Check if the rule specified by xpath is activated."""
    c = config
    for entry in xpath.split("/"):
        c = c.get(entry, {})
    return bool(c.get("activate", False))


def get_anno_rmd(wildcards):
    return 'annotation_ensdb.Rmd' if config["ANNOTATION"] == "EnsDb" else 'annotation_gtf.Rmd'

def get_tenx_type(wildcards):
    """Get matrix type (column name) from sample sheet."""
    cols = ['HDF5_Multiple_Assays', 'RDS_Multiple_Assays', 'Gene.Expression', 'Peaks', 'TF']
    df = samples[samples["sample"] == wildcards.sample]
    if wildcards.replicate != 'nan':
        df = df[df["replicate"] == wildcards.replicate]
    return df[cols].dropna(axis=1).columns.to_list()

def get_tenx(wildcards):
    """Get filtered matrix (hdf5/rds file or mex directory) path from sample sheet."""
    cols = ['HDF5_Multiple_Assays', 'RDS_Multiple_Assays', 'Gene.Expression', 'Peaks', 'TF']
    df = samples[samples["sample"] == wildcards.sample]
    if wildcards.replicate != 'nan':
        df = df[df["replicate"] == wildcards.replicate]
    return df[cols].dropna(axis=1).values.flatten().tolist()

def get_tsv_path(xpath):
    return xpath if os.path.exists(xpath) else ""

def get_groups(xpath):
    """Get group names from selected config section"""
    return list(config.get(xpath, {}).get("groups", {}).keys())

def get_assays(xpath):
    """
    Get assay names from selected config section.
    If using group integrate, need to specify assay_type
    """
    groups = config.get(xpath, {}).get("groups", {})
    # group_vals is a list of dict_values
    assay_names = [v['assay_name'] for v in groups.values()]
    return assay_names


####### rule inputs ###########
def get_cluster_inputs(wildcards):
    """
    Decide input file path for rules `chooser_paral` and `cluster`
    with or without integration
    """
    seurat = wildcards.seurat
    if seurat in get_groups("normalize"):
        return f"results/normalize_reduce_dims/{seurat}/{seurat}.rds"
    else:
        return f"results/integrate/{seurat}.rds"

def get_integrate_inputs(wildcards):
    seurat = "un" + wildcards.seurat
    return f"results/normalize_reduce_dims/{seurat}/{seurat}.rds",

def get_diff_test_inputs(wildcards):
    seurat = wildcards.seurat
    if seurat in get_groups("weighted_nn"):
        return f"results/wnn/{seurat}/clustered_data.rds"  
    else:
        return f"results/cluster/{seurat}/clustered_data.rds"

def determine_input():
    if config["macs2"]["run"] == "Y":
        return "results/add_macs_peaks/seurat.rds"
    elif config["macs2"]["run"] == "N":
        return "results/merge_zinba/seurat.rds"
    else:
        raise ValueError("Incorrect macs2 configuration - set 'Y' or 'N'")


####### valid inputs ##########
# Create a list storing all targets configured for normalization and integration
snn_targets = get_groups("normalize")

if is_activated("integrate"):
    snn_targets.extend(get_groups("integrate"))

# Filter the targets based on MACS2 configuration
if config["macs2"]["run"] == "N":
    # find any unitegrated assays containing "MACS"
    assays_list = get_assays("normalize")
    assays_list.extend(get_assays("integrate"))
    # subset snn_targets based on logicals checking "MACS"
    idx = [item != "MACS" for item in assays_list]
    snn_targets = list(compress(snn_targets, idx))

# Create a dictionary for rule-target pairs
d = {}
for key, value in config.items():
    if isinstance(value, dict):
        if "activate" in value.keys() or key == "normalize":
            d[key] = value["groups"]

valid_groups = {key:list(config[key]['groups'].keys()) for key in d.keys()}

####### cluster inputs ########

cluster_input = []
cluster_input.extend(
    expand(
        "results/cluster/{seurat}/clustered_data.rds",
        seurat=snn_targets
    )
)

if is_activated("weighted_nn"):
    cluster_input.extend(
        expand(
            "results/wnn/{seurat}/clustered_data.rds",
            seurat=valid_groups['weighted_nn']
        )
    )

####### all inputs ############

def all_input(wildcards):
    wanted_input = []

    if is_activated("diff_analysis"):
        wanted_input.extend(
            expand(
                "results/diff_analysis/{seurat}/markers.tsv",
                seurat=valid_groups['diff_analysis']
            )
        )

    if config["macs2"]["run"] == "Y":
        wanted_input.append("results/macs2/NA_treat_pileup.bigwig")
        wanted_input.append("results/macs2/NA_control_lambda.bigwig")

    wanted_input.append(
        "results/combine/seurat_combined.rds"
    )

    return wanted_input


####### rules ###########

rule all:
    input:
        all_input

rule build_annotation:
    """
    This rule builds annotation from EnsDb or generic GTF
    'peaks' input used as placeholder. Reference in annotation_gtf.Rmd'
    commented out.
    Fix later : add something like "len(params.genome) == 1"
    "len(params.genome) == 1" only useful for ATAC Peaks annotation.
    Does not impact sample['genome'] where multi-species is supported.
    """
    input:
        markdown = get_anno_rmd,
    output:
        html = "results/build_annotation/report.html",
        anno_atac = "results/build_annotation/annotation.rds",
    params:
        anno_file = config["ANNO_FILE"],
        genome = samples['genome'].unique().tolist()[0],
    threads: 8
    resources:
        mem_mb=1024 * 40,
        disk_mb=1024 * 20,
        runtime=60
    shell:
        """Rscript -e 'params = list(
                anno_atac = "{output.anno_atac}",
                anno_file = "{params.anno_file}",
                genome = "{params.genome}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}")'
        """

rule create_seurat:
    """
    - creates a single cell obj for RNA and/or ATAC using count matrices
    - filters intersecting cells across the modalities
    - adds samplenames to barcodes
    - adds gene activity to seurat obj
        - TSS enrichment score
        - nucleosome signal
    - calculates mito percentage
    - adds metadata variables assigned in the sample.tsv and aggregates.tsv files
    """
    input:
        markdown = "create_seurat.Rmd",
        tenx = get_tenx,
        annotation = "results/build_annotation/annotation.rds",
    output:
        html = "results/create_seurat/{sample}-{replicate}.report.html",
        seurat = "results/create_seurat/{sample}-{replicate}.seurat_raw.rds"
    params:
        tenx_type = get_tenx_type,
        scriptdir = "scripts",
        sample_tsv = config["samples"],
        aggregates_tsv = get_tsv_path(config["aggregates"]),
        assays_tsv = get_tsv_path(config["assays"]),
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=30
        # mem_mb=1024 * 400
        # disk_mb=1024 * 200
        # runtime=60 * 12
    shell:
        """Rscript -e 'params = list(
                wc_sample = "{wildcards.sample}",
                wc_replicate = "{wildcards.replicate}",
                tenx = "{input.tenx}",
                annotation = "{input.annotation}",
                seurat = "{output.seurat}",
                tenx_type = "{params.tenx_type}",
                scriptdir = "{params.scriptdir}",
                sample_tsv = "{params.sample_tsv}",
                aggregates_tsv = "{params.aggregates_tsv}",
                assays_tsv = "{params.assays_tsv}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}" )'
        """

rule qc:
    """
    - imputes missing values to zero in metadata
    - removes outlier cells based on upper/lower limits in QC metrics
    - creates exploratory violin plots before and after filtering
    """
    input:
        markdown = "qc.Rmd",
        seurat_in = "results/create_seurat/{sample}-{replicate}.seurat_raw.rds",
        config = ancient(configuration)
    output:
        html = "results/qc/{sample}-{replicate}.report.html",
        seurat_out = "results/qc/{sample}-{replicate}.seurat_qc.rds",
    params:
        scriptdir = "scripts",
        outdir = "results/qc",
        intermediates_dir="results/qc/{sample}-{replicate}"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 4
        # mem_mb=1024 * 200
        # disk_mb=1024 * 100
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}",
                scriptdir = "{params.scriptdir}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                intermediates_dir = "{params.intermediates_dir}",
                output_dir = "{params.outdir}",
                output_file = "{output.html}" )'
        rm -rf {params.intermediates_dir}
        """

rule merge_zinba:
    """
    - merge seurat objects from QC in case of skipping macs2 peakcalling
    - update the peak x cell matrices to have identical genomic coordinates 
      in a merged seurat obj across the ATAC datasets if it has multiple ATAC samples
    """
    input:
        markdown = "merge_zinba.Rmd",
        seurats = expand(
            "results/qc/{sample}-{replicate}.seurat_qc.rds",
            zip,
            sample = samples["sample"].tolist(),
            replicate = samples["replicate"].tolist()
            ),
        annotation = "results/build_annotation/annotation.rds"
    output:
        html = "results/merge_zinba/report.html",
        seurat= "results/merge_zinba/seurat.rds"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=30
        # mem_mb=1024 * 200
        # disk_mb=1024 * 100
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params=list(
            seurats="{input.seurats}",
            seurat="{output.seurat}",
            annotation="{input.annotation}");
        rmarkdown::render("{input.markdown}",
        params=params,
        output_file="{output.html}" )'
        """

rule merge_macs_prep:
    """
    - combines all samples in samples.tsv into a single Seurat object.
    - update the peak x cell matrices to have identical genomic coordinates 
      in a merged seurat obj across the ATAC datasets if it has multiple ATAC samples
    - saves fragments as a single bed file for macs2 peak calling
    - NA are imputed for cells lacking counts data.
      Example: Cells containing only GEX data will have NA for all ATAC peaks and vice versa.

    Peakcalling section:
    ZINBA: Combine peaks if needed
    MACS: Call peaks on full data set
    """
    input:
        markdown = "merge_macs_prep.Rmd",
        seurats = expand(
            "results/qc/{sample}-{replicate}.seurat_qc.rds",
            zip,
            sample = samples["sample"].tolist(),
            replicate = samples["replicate"].tolist()
            ),
        annotation = "results/build_annotation/annotation.rds",
        config = ancient(configuration),
    output:
        html = "results/merge_macs_prep/report.html",
        seurat = "results/merge_macs_prep/seurat.rds",
        bed = "results/merge_macs_prep/Multiome.bed",
    params:
        genome = samples['genome'].unique().tolist()[0],
        fragments = samples['fragments'].dropna().tolist(),
        scriptdir = "scripts",
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        # File name written by Signac::SplitFragmentsBy() is variable, add cmd to rename
        """Rscript -e 'params = list(
                seurats = "{input.seurats}",
                annotation = "{input.annotation}",
                config = "{input.config}",
                seurat = "{output.seurat}",
                genome = "{params.genome}",
                fragments = "{params.fragments}",
                scriptdir = "{params.scriptdir}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}" )';
        """
        """
        fragments_bed=($(find results/merge_macs_prep -name *.bed))
        if [[ ! ${{#fragments_bed[@]}} == 1 ]]
        then
            echo "config['macs']['split_frags_by'] choice generates more than 1 output bed file."
            echo "Please set 'split_frags_by' to a samples.tsv column shared across all ATAC/Multiome samples."
        elif [[ ! ${{fragments_bed[0]}} -ef results/merge_macs_prep/Multiome.bed ]]
        then
            echo "Output bed file is not named 'Multiome.bed', which is required for 'macs2' rule. Renaming."
            mv ${{fragments_bed[0]}} {output.bed}
        fi
        """

rule macs2:
    """
    This rule runs macs2 in command line
    """
    input:
        bed = "results/merge_macs_prep/Multiome.bed",
    output:
        tsvgz = "results/macs2/macspeaks.tsv.gz",
        tbi = "results/macs2/macspeaks.tsv.gz.tbi",
        peak = "results/macs2/NA_peaks.narrowPeak",
        signal = "results/macs2/NA_treat_pileup.bdg",
        noise = "results/macs2/NA_control_lambda.bdg"
    params:
        tsv = "results/macs2/macspeaks.tsv"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        # NOTE: parallel takes input using {} and :::
        # {} in snakemake is problematic. Use {{}} for something else if you need it.
        "set +o pipefail; "
        "sort -k 1,1 -k 2 -V -s --parallel={threads} {input.bed} | grep 'chr' | uniq > {params.tsv} && "
        "sort -k 1,1 -k 2 -V -s --parallel={threads} {input.bed} | grep -v 'chr' | uniq >> {params.tsv} && "
        "bgzip --threads {threads} < {params.tsv} > {output.tsvgz} && "
        "parallel --max-procs={threads} "
            "'tabix -p bed --zero-based --force --begin 2 --end 3 {{}}' ::: {output.tsvgz} && "
        "parallel --max-procs={threads} "
            "'macs2 callpeak -t {{}} -f BED --nomodel -B --outdir results/macs2' ::: {output.tsvgz}"

rule add_macs_peaks:
    """
    - updates Seurat obj with MACS-called peaks if present, which adds a new assay labeled MACS
    - adds a pseudo peak matrix with zeros for cells with no peaks called
    """
    input:
        peak = "results/macs2/NA_peaks.narrowPeak",
        seurat = "results/merge_macs_prep/seurat.rds",
        markdown = "add_macs_peaks.Rmd",
        annotation = "results/build_annotation/annotation.rds",
    output:
        html = "results/add_macs_peaks/report.html",
        seurat = "results/add_macs_peaks/seurat.rds",
    params:
        genome = samples['genome'].unique().tolist()[0],
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        """Rscript -e 'params = list(
                seurat = "{input.seurat}",
                seurat_out = "{output.seurat}",
                peak = "{input.peak}",
                annotation = "{input.annotation}",
                genome = "{params.genome}" );
            rmarkdown::render("{input.markdown}",
            params=params,
            output_file = "{output.html}")'
        """

rule chromsizes:
    """
    Creates a chromsizes table from fasta
    """
    input:
        config["macs2"]["fasta"]
    output:
        config["macs2"]["chromsizes"]
    log:
        f'{config["macs2"]["fasta"]}.log'
    params:
        # NOTE: Be careful with the memory here; make sure you have enough
        # and/or it matches the resources you're requesting in the cluster
        # config.
        java_args='-Xmx20g'
        # java_args='-Xmx2g'  # [TEST SETTINGS -1]
    resources:
        mem_mb=1024 * 24,
        disk_mb=1024 * 12,
        runtime=60 * 1
    shell:
        'export LC_COLLATE=C; '
        'rm -f {output}.tmp '
        '&& picard '
        '{params.java_args} '
        'CreateSequenceDictionary R={input} O={output}.tmp &> {log} '
        '&& grep "^@SQ" {output}.tmp '
        '''| awk '{{print $2, $3}}' '''
        '| sed "s/SN://g;s/ LN:/\\t/g" '
        '| sort -k1,1 > {output} '
        '&& rm -f {output}.tmp '


rule bigwig_signal:
    """
    Creates a bigwig file for peak intensity from macs2-generated bedGraph
    """
    input:
        chrom = config["macs2"]["chromsizes"],
        bdg = "results/macs2/NA_treat_pileup.bdg",
    output:
        "results/macs2/NA_treat_pileup.bigwig",
    resources:
        mem_mb=1024 * 20,
        disk_mb=1024 * 10,
        runtime=60 * 1
    shell:
        """
        awk 'NR==FNR {{chr_size[$1]=$2; next}}
             {{if ($3 > chr_size[$1]) $3 = chr_size[$1]; print}}' {input.chrom} {input.bdg} > {input.bdg}.temp
        bedClip {input.bdg} {input.chrom} {input.bdg}.temp
        bedGraphToBigWig {input.bdg}.temp {input.chrom} {output}
        rm {input.bdg}.temp
        """

rule bigwig_noise:
    """
    Creates a bigwig file for noise intensity from macs2-generated bedGraph
    """
    input:
        chrom = config["macs2"]["chromsizes"],
        bdg = "results/macs2/NA_control_lambda.bdg"
    output:
        "results/macs2/NA_control_lambda.bigwig"
    resources:
        mem_mb=1024 * 20,
        disk_mb=1024 * 10,
        runtime=60 * 1
    shell:
        """
        awk 'NR==FNR {{chr_size[$1]=$2; next}}
             {{if ($3 > chr_size[$1]) $3 = chr_size[$1]; print}}' {input.chrom} {input.bdg} > {input.bdg}.temp
        bedClip {input.bdg} {input.chrom} {input.bdg}.temp
        bedGraphToBigWig {input.bdg}.temp {input.chrom} {output}
        rm {input.bdg}.temp
        """



rule normalize_reduce_dims:
    """
    - filters cell barcodes where the counts are non-zero and non-missing in each modality
    - split the Seurat obj into layers
    - performs normalization on the filtered cells for each assay
    - performs dimensionality reduction on the filtered cells in each modality
    - creates an elbow plot per sample per modality

    NOTE: 
    Linear and non-linear dimensional reductions are stored in unique dim red key:
    using format: paste0(assay_name, "_", reduction_type)
    Example("gene.expression_pca").
    """
    input:
        markdown = "normalize_reduce_dims.Rmd",
        seurat_in = determine_input(),
        config = ancient(configuration),
    output:
        html = "results/normalize_reduce_dims/{seurat}/{seurat}.report.html",
        seurat_out = "results/normalize_reduce_dims/{seurat}/{seurat}.rds"
    params:
        scriptdir = "scripts",
        output_dir = "results/normalize_reduce_dims/{seurat}",
        interm_dir = "results/normalize_reduce_dims/intermediates_dir/{seurat}"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}",
                scriptdir = "{params.scriptdir}");
            rmarkdown::render("{input.markdown}",
                params = params,
                output_dir="{params.output_dir}",
                intermediates_dir = "{params.interm_dir}",
                output_file = "{output.html}")'
        rm -rf {params.interm_dir}
        """


rule integrate:
    """
    - runs normalization and dim reduction if it's missing
    - integrates datasets in the same modalities based on sample.tsv or units.tsv
    - create an exploratory elbow plot

    NOTE:
    Add more columns to sample.tsv or units.tsv for new integration combinations.
    """
    input:
        markdown = "integrate.Rmd",
        seurat_in = get_integrate_inputs,
        config = ancient(configuration),
    output:
        html = "results/integrate/{seurat}.report.html",
        seurat_out = "results/integrate/{seurat}.rds",
    threads: 32
    resources:
          mem_mb=1024 * 100,
          disk_mb=1024 * 50,
          runtime=60 * 24
#         mem_mb=1024 * 300,
#         disk_mb=1024 * 150,
#         runtime=60 * 24
    shell:
        """
        ulimit -u 8192;
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}" )'
        """

rule chooser_paral:
    """
    (Optional)
    Runs chooseR for clustering resolution selection to calculate silhouette scores per cluster 
    on iteratively sampled cells

    Reference: https://pubmed.ncbi.nlm.nih.gov/33522897
    """
    input:
        markdown = "chooser_paral.Rmd",
        seurat_in = get_cluster_inputs,
        config = ancient(configuration),
    output:
        html = "results/chooser_run/{seurat}/res_{res}/report.html",
        output_dir = directory("results/chooser_run/{seurat}/res_{res}"),
        calculation_rds = expand("results/chooser_run/{{seurat}}/{sil}_{{res}}.rds", sil=chooser_sil),
        seurat_rds = "results/chooser_run/{seurat}/seurat_obj_{res}.rds",
    params:
        results_path = "results/chooser_run/{seurat}",
        seurat_out = "{seurat}",
        scriptdir = "scripts",
        intermediates_dir = "results/chooser_run/intermediates_dir/{seurat}/res_{res}"
    threads: 12
    resources:
        mem_mb = 1024 * 100,
        disk_mb = 1024 * 50,
        runtime = 720
    conda:
        "chooser/env.yaml"
    shell:
        """
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                calculation_outs = "{output.calculation_rds}",
                seurat_rds = "{output.seurat_rds}",
                seurat_out = "{params.seurat_out}",
                results_path = "{params.results_path}",
                res = "{wildcards.res}",
                scriptdir = "{params.scriptdir}");
            rmarkdown::render("{input.markdown}",
                params = params,
                intermediates_dir = "{params.intermediates_dir}",
                output_dir = "{output.output_dir}",
                output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """

rule chooser_aggr:
    """
    (Optional)
    - creates exploratory plots for individual resolutions and silhouette scores
    - calculates optimal resolution
    """
    input:
        markdown = 'chooser_aggr.Rmd',      # chooser - results
        sil_obj = expand(
            'results/chooser_run/{{seurat}}/{sil}_{res}.rds',
            sil=chooser_sil,
            res=resolutions),
        config = ancient(configuration)
    output:
        html = "results/chooser_plot/{seurat}/report.html",
        output_dir = directory("results/chooser_plot/{seurat}"),
        seurat_rds = "results/chooser_plot/{seurat}/clustered_data.rds",
        choice_rds = "results/chooser_plot/{seurat}/choice.rds",
    params:
        resolutions = resolutions,
        res_path = "results/chooser_run/{seurat}",
        new_path = "results/chooser_plot/{seurat}",
        intermediates_dir = "results/chooser_plot/intermediates_dir/{seurat}",
    conda:
        "chooser/env.yaml"
    threads: 12
    resources:
        mem_mb=1024 * 150,
        disk_mb=1024 * 100,
        runtime=60 * 1
    shell:
        """
        Rscript -e 'params = list(
            sil_obj="{input.sil_obj}",
            results_path="{params.res_path}",
            new_path = "{params.new_path}",
            config = "{input.config}",
            seurat = "{wildcards.seurat}",
            seurat_out = "{output.seurat_rds}",
            choice_out = "{output.choice_rds}");
        rmarkdown::render("{input.markdown}",
            params = params,
            intermediates_dir = "{params.intermediates_dir}",
            output_dir = "{output.output_dir}",
            output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """

rule prep_cluster:
    """
    Prepare an RDS file storing the resolution of clustering

    NOTE: Configure `cluster` in your config.yaml
    """
    input:
        seurat_in = get_cluster_inputs
    output:
        "results/prep_cluster/{seurat}/choice.rds"
    params:
        res_use = user_resolution
    threads: 1
    shell:
        """
        Rscript -e 'res <- {params.res_use}; saveRDS(res, "{output}")'
        """

rule cluster:
    """
    - runs clustering and UMAP
    - creates exploratory UMAP plots
    """
    input:
        markdown = "cluster.Rmd",      # chooser - results
        seurat_in = get_cluster_inputs,
        res_choice = lambda wildcards:( 
            f"results/chooser_plot/{wildcards.seurat}/choice.rds"
            if pd.isnull(user_resolution)
            else f"results/prep_cluster/{wildcards.seurat}/choice.rds"
        ),
        config = ancient(configuration),
    output:
        html = "results/cluster/{seurat}/report.html",
        output_dir = directory("results/cluster/{seurat}"),
        seurat_out = "results/cluster/{seurat}/clustered_data.rds",
        barcodes_out = "results/cluster/{seurat}/barcodes.rds",
    params:
        intermediates_dir = "results/cluster/intermediates_dir/{seurat}"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params = list(
            seurat_in = "{input.seurat_in}",
            config = "{input.config}",
            res_choice = "{input.res_choice}",
            seurat = "{wildcards.seurat}",
            seurat_out = "{output.seurat_out}",
            barcodes_out = "{output.barcodes_out}");
        rmarkdown::render("{input.markdown}",
            params = params,
            intermediates_dir = "{params.intermediates_dir}",
            output_dir = "{output.output_dir}",
            output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """

rule weighted_nn:
    """
    - filters cells existing in both modalities
    - builds a Seurat object consisting of assays and dimensionality reductions for both modalities
    - finds multimodal neighbors
    - runs UMAP and clustering
    - creates exploratory plots
    """
    input:
        markdown = "weighted_nn.Rmd",
        seurats =expand(
            "results/cluster/{seurat}/clustered_data.rds",
            seurat=snn_targets),
        config = ancient(configuration),
    output:
        html = "results/wnn/{seurat}/report.html",
        seurat_out = "results/wnn/{seurat}/clustered_data.rds",
        barcodes_out = "results/wnn/{seurat}/barcodes.rds",
    params:
        scriptdir = "scripts",
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 12
        # mem_mb=1024 * 600,
        # disk_mb=1024 * 300,
        # runtime=60 * 12
    shell:
        """
        ulimit -u 8192;
        Rscript -e 'params = list(
                seurats = "{input.seurats}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}",
                barcodes_out = "{output.barcodes_out}",
                seurat = "{wildcards.seurat}",
                scriptdir = "{params.scriptdir}");
            rmarkdown::render("{input.markdown}",
                params = parameters,
                output_file = "{output.html}")'
        """

rule diff_analysis:
    """
    - computes per-cluster marker genes
    - saves DEGs in a tsv file
    """
    input:
        markdown = "diff_analysis.Rmd",
        seurat_in = get_diff_test_inputs,
        config = ancient(configuration),
    output:
        html = "results/diff_analysis/{seurat}/report.html",
        output_dir = directory("results/diff_analysis/{seurat}"),
        markers_out = "results/diff_analysis/{seurat}/markers.tsv",
    params:
        scriptdir = "scripts",
        intermediates_dir = "results/chooser_plot/intermediates_dir/{seurat}",
    threads: 32
    resources:
        mem_mb=1024 * 100,
         disk_mb=1024 * 50,
         runtime=60 * 12
        # mem_mb=1024 * 500,
        # disk_mb=1024 * 250,
        # runtime=60 * 24
    shell:
        """
        ulimit -u 8192;
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                markers_out = "{output.markers_out}",
                seurat = "{wildcards.seurat}",
                scriptdir = "{params.scriptdir}");
            rmarkdown::render("{input.markdown}",
                params = parameters,
                intermediates_dir = "{params.intermediates_dir}",
                output_dir = "{output.output_dir}",
                output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """

rule combine:
    """
    - merges all dimensionality reductions and metadata info created during rules cluster
      and weighted_nn (if present) into one Seurat objects
    - returns a list of Seurat objects
    - Seurat objects are combined only if they contain identical barcodes
    """
    input:
        markdown = "combine.Rmd",
        seurats = cluster_input,
        config = ancient(configuration),
    output:
        html = "results/combine/report.html",
        seurat_out = "results/combine/seurat_combined.rds",
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 1000,
        # disk_mb=1024 * 500,
        # runtime=60 * 24
    shell:
        """Rscript -e 'params = list(
                seurats = "{input.seurats}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}");
            rmarkdown::render("{input.markdown}",
                params = parameters,
                output_file = "{output.html}")'
        """

# Add downstream analyses here with combined object.
# Be sure to append output file to "wanted_input" list.
######################################################

rule build_guide:
    """
    Builds initial version of guide.rst
    """
    input:
        "config/other-setup/guide_template.rst"
    output:
        "../report/guide.rst"
    params:
        sampletable = config["samples"]
    resources:
        mem_mb=1024 * 20,
        disk_mb=1024 * 10,
        runtime=10
    shell:
        # returns guide.rst with report.html file paths in the results directory
        """
        find results -print | grep report.html > reportlist.txt
        cat {params.sampletable} | tr '[:space:]' '[\n*]' | grep / > cellrangerlist.txt
        while read p
        do
            if [[ "$p" == "Downstream output reports" ]]
            then
                echo "$p\n" >> {output}
                while read l
                do
                    # update result name
                    result_name=$(dirname "$l" | sed 's/results\///')
                    line="$l"
                    # escape bash variables by doubling them
                    echo "- \`${{result_name}} <${{line}}>\`_\n" >> {output}
                done < reportlist.txt
            elif [[ "$p" == "Cellranger output directory" ]]
            then
                echo "$p\n" >> {output}
                while read f
                do
                    file='- `cellranger_output <'"$f"'>`_\n'
                    echo "$file" >> {output}
                done < cellrangerlist.txt
            elif [[ "$p" == ":local:" ]]
            then
                echo "\t:local:" >> {output}
            else
                echo "$p" >> {output}
            fi
        done < {input}
        rm reportlist.txt cellrangerlist.txt
        """


