import pandas as pd
import numpy as np
import os
from itertools import compress

##### for interactive debugging
# import yaml
# with open("config/multiome-config/config.yaml", 'r') as stream:
#     config = yaml.safe_load(stream)


##### load config and sample sheets #####
configfile: "config/multiome-config/config.yaml"


# configuration = "config/config.yaml"
# workflow.configfiles generates a list
# in this case, starts with ["config/config.yaml"]
# any files in snakemake --configfile are added by "list.insert(0, x)"
# so snakemake --configfile test.yaml test1.yaml will return:
# ["test1.yaml", "test.yaml", "config/config.yaml"]
configuration = workflow.configfiles[0]


# print(workflow.configfiles)   # uncomment for testing
# print(configuration)      # uncomment for testing

# using Rmarkdown outputs as guide/report
# report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


samples = pd.read_table(config["samples"]).set_index(["sample", "replicate"], drop=False)
samples.index.names = ["sample", "replicate"]
samples.index = samples.index.set_levels(
    [i.astype(str) for i in samples.index.levels]
)  # enforce str in index
# print(samples)

# Set chooser variables
resolutions = config['chooser']['resolutions']
chooser_sil = config['chooser']['silhouette']
user_resolution = config['cluster']['resolution']


####### helpers ###########

def is_activated(xpath):
    """Check if the rule specified by xpath is activated."""
    c = config
    for entry in xpath.split("/"):
        c = c.get(entry, {})
    return bool(c.get("activate", False))


def get_anno_rmd(wildcards):
    return 'annotation_ensdb.Rmd' if config["ANNOTATION"] == "EnsDb" else 'annotation_gtf.Rmd'

def get_tenx_type(wildcards):
    """Get matrix type (column name) from sample sheet."""
    cols = ['HDF5_Multiple_Assays', 'RDS_Multiple_Assays', 'Gene.Expression', 'Peaks', 'TF']
    df = samples[samples["sample"] == wildcards.sample]
    if wildcards.replicate != 'nan':
        df = df[df["replicate"] == wildcards.replicate]
    return df[cols].dropna(axis=1).columns.to_list()

def get_tenx(wildcards):
    """Get filtered matrix (hdf5/rds file or mex directory) path from sample sheet."""
    cols = ['HDF5_Multiple_Assays', 'RDS_Multiple_Assays', 'Gene.Expression', 'Peaks', 'TF']
    df = samples[samples["sample"] == wildcards.sample]
    if wildcards.replicate != 'nan':
        df = df[df["replicate"] == wildcards.replicate]
    return df[cols].dropna(axis=1).values.flatten().tolist()

def get_tsv_path(xpath):
    return xpath if os.path.exists(xpath) else ""

def get_groups(xpath):
    """Get group names from selected config section"""
    return list(config.get(xpath, {}).get("groups", {}).keys())

def get_assays(xpath):
    """
    Get assay names from selected config section.
    If using group integrate, need to specify assay_type
    """
    groups = config.get(xpath, {}).get("groups", {})
    # group_vals is a list of dict_values
    assay_names = [v['assay_name'] for v in groups.values()]
    return assay_names


####### rule inputs ###########
def get_cluster_inputs(wildcards):
    """
    Decide input file path for rules `chooser_paral` and `cluster`
    with or without integration
    """
    seurat = wildcards.seurat
    if seurat in get_groups("normalize"):
        return f"results/normalize_reduce_dims/{seurat}/{seurat}.rds"
    else:
        return f"results/integrate/{seurat}.rds"

def get_integrate_inputs(wildcards):
    seurat = "un" + wildcards.seurat
    return f"results/normalize_reduce_dims/{seurat}/{seurat}.rds",


def get_diff_test_input(wildcards):
    seurat = wildcards.seurat
    weighted_nn_list = get_groups("weighted_nn")
    if seurat in weighted_nn_list:
        return "results/wnn/{seurat}/clustered_data.rds"  
    else:
        return "results/cluster/{seurat}/clustered_data.rds"

def determine_input():
    if config["macs2"]["run"] == "Y":
        return "results/add_macs_peaks/seurat.rds"
    elif config["macs2"]["run"] == "N":
        return "results/merge_zinba/seurat.rds"
    else:
        raise ValueError("Incorrect macs2 configuration - set 'Y' or 'N'")


####### valid inputs ##########
# Create a list storing all targets configured for normalization and integration
snn_targets = get_groups("normalize")

if is_activated("integrate"):
    snn_targets.extend(get_groups("integrate"))

# Filter the targets based on MACS2 configuration
if config["macs2"]["run"] == "N":
    # find any unitegrated assays containing "MACS"
    assays_list = get_assays("normalize")
    assays_list.extend(get_assays("integrate"))
    # subset snn_targets based on logicals checking "MACS"
    idx = [item != "MACS" for item in assays_list]
    snn_targets = list(compress(snn_targets, idx))

# Create a dictionary for rule-target pairs
d = {}
for key, value in config.items():
    if isinstance(value, dict):
        if "activate" in value.keys() or key == "normalize":
            d[key] = value["groups"]

valid_groups = {key:list(config[key]['groups'].keys()) for key in d.keys()}

####### cluster inputs ########

cluster_input = []
cluster_input.extend(
    expand(
        "results/cluster/{seurat}/clustered_data.rds",
        seurat=snn_targets
    )
)

if is_activated("weighted_nn"):
    cluster_input.extend(
        expand(
            "results/wnn/{seurat}/clustered_data.rds",
            seurat=valid_groups['weighted_nn']
        )
    )

####### all inputs ############

def all_input(wildcards):
    wanted_input = []

    if is_activated("diff_analysis"):
        wanted_input.extend(
            expand(
                "results/diff_analysis/{seurat}/markers.tsv",
                seurat=valid_groups['diff_analysis']
            )
        )

    wanted_input.append(
        "results/combine/seurat_combined.rds"
    )

    if config["guide"] == "build":
        wanted_input.append(
            "../report/guide.rst"
        )
    elif config["guide"] == "render":
        wanted_input.append(
            "../report/guide.html"
        )

    return wanted_input


####### rules ###########

rule all:
    input:
#         expand("results/chooser_run/{seurat}/seurat_obj_{res}.rds", seurat=snn_targets, res=resolutions),
#         expand("results/chooser_plot/{seurat}/clustered_data.rds", seurat=snn_targets),
        expand("results/cluster/{seurat}/clustered_data.rds", seurat=snn_targets)


rule build_annotation:
    """
    This rule builds annotation from EnsDb or generic GTF
    'peaks' input used as placeholder. Reference in annotation_gtf.Rmd'
    commented out.
    Fix later : add something like "len(params.genome) == 1"
    "len(params.genome) == 1" only useful for ATAC Peaks annotation.
    Does not impact sample['genome'] where multi-species is supported.
    """
    input:
        markdown = get_anno_rmd,
    output:
        html = "results/build_annotation/report.html",
        anno_atac = "results/build_annotation/annotation.rds",
    params:
        anno_file = config["ANNO_FILE"],
        genome = samples['genome'].unique().tolist()[0],
    threads: 8
    resources:
        mem_mb=1024 * 40,
        disk_mb=1024 * 20,
        runtime=60
    shell:
        """Rscript -e 'params = list(
                anno_atac = "{output.anno_atac}",
                anno_file = "{params.anno_file}",
                genome = "{params.genome}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}")'
        """

rule create_seurat:
    """
    Creates a seurat object with associated assays.
    """
    input:
        markdown = "create_seurat.Rmd",
        tenx = get_tenx,
        annotation = "results/build_annotation/annotation.rds",
    output:
        html = "results/create_seurat/{sample}-{replicate}.report.html",
        seurat = "results/create_seurat/{sample}-{replicate}.seurat_raw.rds"
    params:
        tenx_type = get_tenx_type,
        scriptdir = "scripts",
        sample_tsv = config["samples"],
        aggregates_tsv = get_tsv_path(config["aggregates"]),
        assays_tsv = get_tsv_path(config["assays"]),
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=30
        # mem_mb=1024 * 400
        # disk_mb=1024 * 200
        # runtime=60 * 12
    shell:
        """Rscript -e 'params = list(
                wc_sample = "{wildcards.sample}",
                wc_replicate = "{wildcards.replicate}",
                tenx = "{input.tenx}",
                annotation = "{input.annotation}",
                seurat = "{output.seurat}",
                tenx_type = "{params.tenx_type}",
                scriptdir = "{params.scriptdir}",
                sample_tsv = "{params.sample_tsv}",
                aggregates_tsv = "{params.aggregates_tsv}",
                assays_tsv = "{params.assays_tsv}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}" )'
        """

rule qc:
    """
    Filters cell counts based on user-supplied column names present in Seurat metadata.
    Saves pre- and post-filtered violin plots if user wants to generate report later.

    Do this step individually, in case need to re-run QC/filtering with diff params.
    Little bit of I/O overhead worth it.
    """
    input:
        markdown = "qc.Rmd",
        seurat_in = "results/create_seurat/{sample}-{replicate}.seurat_raw.rds",
        config = ancient(configuration)
    output:
        html = "results/qc/{sample}-{replicate}.report.html",
        seurat_out = "results/qc/{sample}-{replicate}.seurat_qc.rds",
    params:
        scriptdir = "scripts",
        outdir = "results/qc",
        intermediates_dir="results/qc/{sample}-{replicate}"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 4
        # mem_mb=1024 * 200
        # disk_mb=1024 * 100
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}",
                scriptdir = "{params.scriptdir}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                intermediates_dir = "{params.intermediates_dir}",
                output_dir = "{params.outdir}",
                output_file = "{output.html}" )'
        rm -rf {params.intermediates_dir}
        """

rule merge_zinba:
    """
    Merge seurat objects from QC in case of skipping macs2 peakcalling
    """
    input:
        markdown = "merge_zinba.Rmd",
        seurats = expand(
            "results/qc/{sample}-{replicate}.seurat_qc.rds",
            zip,
            sample = samples["sample"].tolist(),
            replicate = samples["replicate"].tolist()
            ),
        annotation = "results/build_annotation/annotation.rds"
    output:
        html = "results/merge_zinba/report.html",
        seurat= "results/merge_zinba/seurat.rds"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=30
        # mem_mb=1024 * 200
        # disk_mb=1024 * 100
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params=list(
            seurats="{input.seurats}",
            seurat="{output.seurat}",
            annotation="{input.annotation}");
        rmarkdown::render("{input.markdown}",
        params=params,
        output_file="{output.html}" )'
        """

rule merge_macs_prep:
    """
    Merge section:
    Combines all samples in samples.tsv into a single Seurat object.
    This improves consistency across all assays/samples.
    If multiple peaks files from select_peaks rule are found, performs granges reduction.
    Note that NA are imputed for cells lacking counts data.
    Example: Cells containing only GEX data will have NA for all ATAC peaks and vice versa.

    Peakcalling section:
    ZINBA: Combine peaks if needed
    MACS: Call peaks on full data set
    """
    input:
        markdown = "merge_macs_prep.Rmd",
        seurats = expand(
            "results/qc/{sample}-{replicate}.seurat_qc.rds",
            zip,
            sample = samples["sample"].tolist(),
            replicate = samples["replicate"].tolist()
            ),
        annotation = "results/build_annotation/annotation.rds",
        config = ancient(configuration),
    output:
        html = "results/merge_macs_prep/report.html",
        seurat = "results/merge_macs_prep/seurat.rds",
        bed = "results/merge_macs_prep/Multiome.bed",
    params:
        genome = samples['genome'].unique().tolist()[0],
        fragments = samples['fragments'].dropna().tolist(),
        scriptdir = "scripts",
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        # File name written by Signac::SplitFragmentsBy() is variable, add cmd to rename
        """Rscript -e 'params = list(
                seurats = "{input.seurats}",
                annotation = "{input.annotation}",
                config = "{input.config}",
                seurat = "{output.seurat}",
                genome = "{params.genome}",
                fragments = "{params.fragments}",
                scriptdir = "{params.scriptdir}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}" )';
        """
        """
        fragments_bed=($(find results/merge_macs_prep -name *.bed))
        if [[ ! ${{#fragments_bed[@]}} == 1 ]]
        then
            echo "config['macs']['split_frags_by'] choice generates more than 1 output bed file."
            echo "Please set 'split_frags_by' to a samples.tsv column shared across all ATAC/Multiome samples."
        elif [[ ! ${{fragments_bed[0]}} -ef results/merge_macs_prep/Multiome.bed ]]
        then
            echo "Output bed file is not named 'Multiome.bed', which is required for 'macs2' rule. Renaming."
            mv ${{fragments_bed[0]}} {output.bed}
        fi
        """

rule macs2:
    """
    This rule runs macs2 in command line
    """
    input:
        bed = "results/merge_macs_prep/Multiome.bed",
    output:
        tsvgz = "results/macs2/macspeaks.tsv.gz",
        tbi = "results/macs2/macspeaks.tsv.gz.tbi",
        peak = "results/macs2/NA_peaks.narrowPeak",
    params:
        tsv = "results/macs2/macspeaks.tsv"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        # NOTE: parallel takes input using {} and :::
        # {} in snakemake is problematic. Use {{}} for something else if you need it.
        "set +o pipefail; "
        "sort -k 1,1 -k 2 -V -s --parallel={threads} {input.bed} | grep 'chr' | uniq > {params.tsv} && "
        "sort -k 1,1 -k 2 -V -s --parallel={threads} {input.bed} | grep -v 'chr' | uniq >> {params.tsv} && "
        "bgzip --threads {threads} < {params.tsv} > {output.tsvgz} && "
        "parallel --max-procs={threads} "
            "'tabix -p bed --zero-based --force --begin 2 --end 3 {{}}' ::: {output.tsvgz} && "
        "parallel --max-procs={threads} "
            "'macs2 callpeak -t {{}} -f BED --nomodel --outdir results/macs2' ::: {output.tsvgz}"

rule add_macs_peaks:
    """
    This rule merges macs2-called peaks to seurat
    """
    input:
        peak = "results/macs2/NA_peaks.narrowPeak",
        seurat = "results/merge_macs_prep/seurat.rds",
        markdown = "add_macs_peaks.Rmd",
        annotation = "results/build_annotation/annotation.rds",
    output:
        html = "results/add_macs_peaks/report.html",
        seurat = "results/add_macs_peaks/seurat.rds",
    params:
        genome = samples['genome'].unique().tolist()[0],
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        """Rscript -e 'params = list(
                seurat = "{input.seurat}",
                seurat_out = "{output.seurat}",
                peak = "{input.peak}",
                annotation = "{input.annotation}",
                genome = "{params.genome}" );
            rmarkdown::render("{input.markdown}",
            params=params,
            output_file = "{output.html}")'
        """

rule normalize_reduce_dims:
    """
    Pre-process unitegrated data.
    Splits Seurat object from combine_seurat into a list of Seurat objects,
    each object containing 1 assay. Checks for and removes imputed zero values
    generated during combine_seruat step to retain only 'true' counts,
    (the imputed zeros are very problematic).
    For each assay, perform log, sct or lsi normalization. One norm per assay.
    Linear and non-linear dimensional reductions are stored in unique dim red key:
    using format: paste0(assay_name, "_", reduction_type)
    Example("gene.expression_pca").
    Rule returns a list of Seurat objects, each element containing one assay.
    Exception is when 2 assays have identical cells (Multiome, CITE-Seq),
    in which case, will the list element will be a seruat object containing
    all assays with equal cell count (Seurat object with 2 assays.)
    Fix later: This behavior should probably be changed to ensure
    each output list element contains Seurat object with one and only one assay.
    Fix later: If each list element contains only one assay,
    possibly change dim reduction keys to 'pca/lsi' or 'umap' for easy access
    in downstream rules easier to fix. Check if this is viable.
    """
    input:
        markdown = "normalize_reduce_dims.Rmd",
        seurat_in = determine_input(),
        config = ancient(configuration),
    output:
        html = "results/normalize_reduce_dims/{seurat}/{seurat}.report.html",
        seurat_out = "results/normalize_reduce_dims/{seurat}/{seurat}.rds"
    params:
        scriptdir = "scripts",
        output_dir = "results/normalize_reduce_dims/{seurat}",
        interm_dir = "results/normalize_reduce_dims/intermediates_dir/{seurat}"
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}",
                scriptdir = "{params.scriptdir}");
            rmarkdown::render("{input.markdown}",
                params = params,
                output_dir="{params.output_dir}",
                intermediates_dir = "{params.interm_dir}",
                output_file = "{output.html}")'
        rm -rf {params.interm_dir}
        """


rule integrate:
    """
    Perform one or more integration based on sample.tsv or units.tsv columns.
    Note that imputed zeros from combine_seruat rule are note used for integration.
    Fix later: check if imputed zeros still exist and possibly remove from the
    pre- and/or post-integrated objects.
    Add more columns to sample.tsv or units.tsv for new integration combinations.
    Returns list of Seurat objects, each object contains one integration.
    """
    input:
        markdown = "integrate.Rmd",
        # seurat_in = "results/normalize_reduce_dims/un{seurat}/un{seurat}.rds",
        seurat_in = get_integrate_inputs,
        config = ancient(configuration),
    output:
        html = "results/integrate/{seurat}.report.html",
        seurat_out = "results/integrate/{seurat}.rds",
    threads: 32
    resources:
          mem_mb=1024 * 100,
          disk_mb=1024 * 50,
          runtime=60 * 24
#         mem_mb=1024 * 300,
#         disk_mb=1024 * 150,
#         runtime=60 * 24
    shell:
        """
        ulimit -u 8192;
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                seurat_out = "{output.seurat_out}" );
            rmarkdown::render("{input.markdown}",
                params = params,
                output_file = "{output.html}" )'
        """

rule chooser_paral:
    """
    Runs chooseR for clustering resolution selection.
    """
    input:
        markdown = "chooser_paral.Rmd",
        seurat_in = get_cluster_inputs,
        config = ancient(configuration),
    output:
        html = "results/chooser_run/{seurat}/res_{res}/report.html",
        output_dir = directory("results/chooser_run/{seurat}/res_{res}"),
        calculation_rds = expand("results/chooser_run/{{seurat}}/{sil}_{{res}}.rds", sil=chooser_sil),
        seurat_rds = "results/chooser_run/{seurat}/seurat_obj_{res}.rds",
    params:
        results_path = "results/chooser_run/{seurat}",
        seurat_out = "{seurat}",
        scriptdir = "scripts",
        intermediates_dir = "results/chooser_run/intermediates_dir/{seurat}/res_{res}"
    threads: 12
    resources:
        mem_mb = 1024 * 100,
        disk_mb = 1024 * 50,
        runtime = 720
    conda:
        "chooser/env.yaml"
    shell:
        """
        Rscript -e 'params = list(
                seurat_in = "{input.seurat_in}",
                config = "{input.config}",
                calculation_outs = "{output.calculation_rds}",
                seurat_rds = "{output.seurat_rds}",
                seurat_out = "{params.seurat_out}",
                results_path = "{params.results_path}",
                res = "{wildcards.res}",
                scriptdir = "{params.scriptdir}");
            rmarkdown::render("{input.markdown}",
                params = params,
                intermediates_dir = "{params.intermediates_dir}",
                output_dir = "{output.output_dir}",
                output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """

rule chooser_aggr:
    """
    Plots chooseR results
    """
    input:
        markdown = 'chooser_aggr.Rmd',      # chooser - results
        sil_obj = expand(
            'results/chooser_run/{{seurat}}/{sil}_{res}.rds',
            sil=chooser_sil,
            res=resolutions),
        config = ancient(configuration)
    output:
        html = "results/chooser_plot/{seurat}/report.html",
        output_dir = directory("results/chooser_plot/{seurat}"),
        seurat_rds = "results/chooser_plot/{seurat}/clustered_data.rds",
        choice_rds = "results/chooser_plot/{seurat}/choice.rds",
    params:
        resolutions = resolutions,
        res_path = "results/chooser_run/{seurat}",
        new_path = "results/chooser_plot/{seurat}",
        intermediates_dir = "results/chooser_plot/intermediates_dir/{seurat}",
    conda:
        "chooser/env.yaml"
    threads: 12
    resources:
        mem_mb=1024 * 150,
        disk_mb=1024 * 100,
        runtime=60 * 1
    shell:
        """
        Rscript -e 'params = list(
            sil_obj="{input.sil_obj}",
            results_path="{params.res_path}",
            new_path = "{params.new_path}",
            config = "{input.config}",
            seurat = "{wildcards.seurat}",
            seurat_out = "{output.seurat_rds}",
            choice_out = "{output.choice_rds}");
        rmarkdown::render("{input.markdown}",
            params = params,
            intermediates_dir = "{params.intermediates_dir}",
            output_dir = "{output.output_dir}",
            output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """

rule cluster:
    """
    Cluster each unintegrated or integrated assay based on Chooser results
    """
    input:
        markdown = "cluster.Rmd",      # chooser - results
        seurat_in = get_cluster_inputs,
        res_choice = "results/chooser_plot/{seurat}/choice.rds",
        config = ancient(configuration),
    output:
        html = "results/cluster/{seurat}/report.html",
        output_dir = directory("results/cluster/{seurat}"),
        seurat_out = "results/cluster/{seurat}/clustered_data.rds",
        barcodes_out = "results/cluster/{seurat}/barcodes.rds",
    params:
        intermediates_dir = "results/cluster/intermediates_dir/{seurat}",
        res_use = config["cluster"]["resolution"]
    threads: 12
    resources:
        mem_mb=1024 * 100,
        disk_mb=1024 * 50,
        runtime=60 * 24
        # mem_mb=1024 * 200,
        # disk_mb=1024 * 100,
        # runtime=60 * 24
    shell:
        """
        Rscript -e 'params = list(
            seurat_in = "{input.seurat_in}",
            config = "{input.config}",
            res_choice = "{input.res_choice}",
            seurat = "{wildcards.seurat}",
            res_use = "{params.res_use}",
            seurat_out = "{output.seurat_out}",
            barcodes_out = "{output.barcodes_out}");
        rmarkdown::render("{input.markdown}",
            params = params,
            intermediates_dir = "{params.intermediates_dir}",
            output_dir = "{output.output_dir}",
            output_file = "{output.html}")'
        rm -rf {params.intermediates_dir}
        """
