---
title: "Weighted Nearest Neighbor Analysis"
output:
    html_document:
            toc: true
            toc_float: true
            code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    warning=FALSE,
    message=FALSE
    )

```

```{r packages_and_functions, include=FALSE}
library(tidyverse)
library(Signac)
library(Seurat)
library(knitr)
library(future)
library(parallel)
set.seed(1234)

source('common.R')
```


```{r parallelize, include=FALSE}

# Assign the number of cores for parallelization
ncpus <- future::availableCores()

# Adjust max memory allowed
options(future.globals.maxSize=40000 * 1024^2,
        mc.cores=ncpus)

# Parallelize the run
plan("multicore", workers=ncpus)
```

# Set variables

We'll get all the sample and replicate specific variables listed in samples.tsv and units.tsv, respectively. 
We'll also set paths to input files.

```{r variables}
seurat_inputs <- unlist(strsplit(params[['seurats']], ' '))
print('Input Seurat objects:')
print(seurat_inputs)

config_path <- params[['config']]
```

```{r input_config}
config <- yaml::read_yaml(file = config_path)

toydataset <- config[['dataset_size']][['toydataset']]
```


```{r get_analysis_group}

group <- config[['weighted_nn']][['groups']][[params[["seurat"]]]]

group_name <- params[["seurat"]]
print(paste('Current group:', group_name))

targets <- group[['input_groups']]
idx <- grepl(pattern = paste(paste0('/', targets), collapse = "|"), seurat_inputs)
seurat_inputs <- seurat_inputs[idx]

comm_detection <- group[['detection_method']]

print('Seurat objects in use:')
print(seurat_inputs)


```

# Read in data

Read in Seurat objects.

```{r input_seurat}

# Import Seurat objects
seurat_list <- mclapply(seurat_inputs, readRDS) %>%
    set_names(sapply(seurat_inputs, str_split_i, "/", 3))

print('Input sample list:')
print(seurat_list)
```


# Cluster


```{r cluster}

reductions <- group[['reduction']]

print(paste('Configured dimensionality reductions:', paste(reductions, collapse=", ")))

umap_dims <- group[['umap_dims']]
print('Dimension ranges:')
print(umap_dims)


# Create a list storing serial integers for the min to max dimensions
if (!any(is.integer(unlist(umap_dims)))) {
    dims_list <- lapply(seq_along(seurat_list), function(x) 1:50)
} else {
    if (is.list(umap_dims)) {
        dims_list <- lapply(umap_dims, function(l) l[1]:l[2])
    } else {
        # Break if dimension is not correctly configured
        stop("Wrong dimensions! Check your umap_dims in weighted_nn.")
    }
}

names(dims_list) <- names(seurat_list)

print('Dimensions for each modality:')
print(dims_list)

# Determine resolution for clustering
res <- group[['resolution']]

# Set the resolution to 0.8 if it's not configured by user
if (is.null(res)) {
    res <- 0.8
}

print(paste('Resolution:', res))

# Create a vector for barcodes found in both modalities
common_names <- intersect(colnames(seurat_list[[1]]), colnames(seurat_list[[2]]))

if (length(common_names) > 0) {
    print('Common barcodes found for selected assays. Starting weighted NN graphing')
    print('--------------------------------------------------------------------------')
    
    # Create a list storing the names of dimensionality reductions other than UMAP
    reducs_present <- lapply(seurat_list, function(obj) {
        dr_names <- names(obj@reductions)
        idx <- !(dr_names %in% "umap")
        return(dr_names[idx])
    })

    print('All dim reductions present in each seurat object:')
    print(reducs_present)
    print('--------------------------------------------------------------------------')
    
    # Create a vector for indices between configured and available dimensionality reductions
    idx <- sapply(seq_along(reductions), function(x) {
        idy <- which(reductions %in% reducs_present[[x]])
        return(idy)
    })
    
    # Break if any of the configured dimensionality reduction is missing in the current Seurat obj
    if (length(idx) < 2) {
        stop("Not all reductions listed in config file found in input objects!")
    }
    
    # Ensure to have only common cells across the modalities
    seurat_list <- mclapply(seurat_list, subset, cells=common_names)
    
    # Create a list storing each assay
    assay_list <- mclapply(seurat_list, function(obj) {
        red <- reductions[reductions %in% names(obj@reductions)]
        assay_used <- obj@reductions[[red]]@assay.used
        assay <- obj@assays[[assay_used]]
        dr <- obj[[red]]
        dr_name <- paste0(red, assay_used)
        list(
            'red'=red,
            'assay_used'=assay_used,
            'assay'=assay,
            'dr'=dr,
            'dr_name'=dr_name)
    }) %>%
    set_names(names(seurat_list))

    print("Assays extracted:")
    print(lapply(assay_list, summary))

    print('--------------------------------------------------------------------------')

    # Create a merged seurat obj for both modalities
    seurat <- seurat_list[[1]]
    seurat[[assay_list[[2]][['assay_used']]]] <- assay_list[[2]][['assay']]
    for (l in assay_list) { seurat[[l[['dr_name']]]] <- l[['dr']] }

    # Create a list storing dimensionality reductions that will be
    # used to compute multimodal neighbors
    reduc_list <- lapply(assay_list, function(l) l[['dr_name']])
    print("Dimensionality reductions used to compute multimodal neighbors:")
    print(reduc_list)

    print('--------------------------------------------------------------------------')

    # Determine k
    if (toydataset) {
        k.nn <- 5
        k.range <- 50
    } else {
        k.nn <- 20         # Seurat default for FindMultiModalNeighbors
        k.range <- 200     # Seurat default for FindMultiModalNeighbors
    }
    
    print(paste("Number of multimodal neighbors:", k.nn))
    print(paste("Number of approximate neighbors to compute:", k.range))


    # Find multimodal neighbors
    seurat <- FindMultiModalNeighbors(
        object = seurat,
        reduction.list = reduc_list,
        dims.list = dims_list,
        k.nn=k.nn,
        knn.range=k.range,
        verbose=FALSE
    )
    
    # Run UMAP
    seurat <- RunUMAP(
        object = seurat,
        nn.name = "weighted.nn",
        reduction.name = "wnn_umap",
        reduction.key = "wnnUMAP_",
        verbose=FALSE
    )

    # Run clustering
    comm_detection <- ifelse(is.null(comm_detection), 3, comm_detection)
    comm_label <- ifelse(comm_detection == 1, "Louvain", ifelse(
        comm_detection == 2, "Louvain with multilevel refinement", ifelse(
        comm_detection == 3, "Smart local moving (SLM)", ifelse(
        comm_detection == 4, "Leiden", "Undetermined"
    ))))

    print('--------------------------------------------------------------------------')

    if (comm_label == "Undetermined") {
        stop("Wrong method for algorithm parameter in FindCluster function! Check yoru configuration.")
    } else {
        print(paste("WNN clustering performed using modularity optimization method no.", comm_detection))
        print(paste("This will run", comm_label))
        print("See the following reference for more info:")
        print("Ludo Waltmana and Nees Jan van Eck, Eur. Phys. J. B (2013)")
        print("https://link.springer.com/article/10.1140/epjb/e2013-40829-0")
    }
    seurat <- FindClusters(
        object = seurat,
        graph.name = "wsnn",
        algorithm = comm_detection,
        resolution = res,
        verbose=FALSE
    )
} else {
    seurat <- NULL
    print("Multimodal analysis is unavailable because input datasets do not have common cells.")
}

```


# Visualize {.tabset}

```{r umap, results='asis'}

for (name in c("orig.ident", "seurat_clusters")) {
    p <- DimPlot(
      seurat,
      reduction = "wnn_umap",
      pt.size = 0.5,
      group.by = name
    )

    cat('\n\n##', name, '\n\n')
    print(p)
    cat('\n\n')
}
```


# Save Seurat object

```{r save}

# save main seurat object
saveRDS(object=seurat, file=params[['seurat_out']])
print(paste("Seurat object saved:", params[["seurat_out"]]))

# save barcodes for later use (combining multiple processed objects)
barcodes <- colnames(seurat)
saveRDS(object=barcodes, file=params[['barcodes_out']])
print(paste("Barcodes saved:", params[['barcodes_out']]))
```


## Session Info

```{r session_info}
sessionInfo()
```

