# Define path to file containing outputs of cellranger-arc
# Sample based data should be included in a samples.tsv file that contains one row per sample.
#   All columns are strings
# sample: sample name
# replicate: technical replicates from a sample. One line per ('sample', 'replicate') combination
# feature_type: assay/modality
#   Currently supported feature_types: 'Gene.Expression', 'Multiplexing.Capture', 'Peaks', 'Multiome'
samples: config/multiome-config/samples.tsv

# Barcode suffix/ibrary ID mappings should be included in a aggregates.tsv file.
#   This is only needed for cellranger/cellranger-atac/cellranger-arc aggr outputs.
#   Each line contains sample/replicate info identical to samples.tsv entries.
#   'library_id' is taken from cellranger aggregates.tsv, 'bc_suffix' is rownumber or 'library_id' (1 based)
aggregates: config/multiome-config/aggregates.tsv

# Additional assay info should be included in an assays.tsv file that contains one row per assay per sample/rep.
# Only include "DIY" custom count matrices, any "core" cellranger matrices/assays are included in 'samples.tsv'.
assays: config/multiome-config/assays.tsv




# Choose how to build your annotation (e.g. EnsDb or GTF)
# if "GTF", provide path to annotation file, otherwise null.
ANNOTATION: "EnsDb"
ANNO_FILE: "path/to/gene.gtf.gz"

# Feature based QC filtering of cells.
# rm_outliers_method: Detect outliers using standard deviation 'sd' or Tukey's interquartile ranger 'iqr'.
#
# meta_labels: Which metadata columns to use for filtering?
#   Can select from 'feature_type' in samples.tsv, or any column in units.tsv excluding 'sample' and 'unit'.
#
# lower: Key:value pairs of metadata column and associated lower limit for cutoff, below which exclude cells.
#   If present, overrides lower limit detected by outlier method.
#   If null, outlier method tries to remove cells automatically
#
# upper: Key:value pairs of metadata column and associated upper limit for cutoff, above which exclude cells.
#   If present, overrides upper limit detected by outlier method.
#   If null, outlier method tries to remove cells automatically
qc:
  remove_outliers: true
  rm_outliers_method: sd
  meta_labels:
    - nCount_Gene.Expression
    - nCount_Peaks
    - percent.mt
    - TSS.enrichment
  lower: 
    nCount_Gene.Expression: 100
    nCount_Peaks: 1000
    TSS.enrichment: 2
  upper: null


# Determine whether or not to run macs2 (Y or N)
# If run macs, which metadata column to split fragments by (currently, any columns in 'samples.tsv' supported)
macs2:
  run: "Y"
  group_fragments_by: genome # feature_type


# Normalization and linear reduction
#
# split_by: metadata column to split, match the split_by in the `integrate`
#
# groups: Each group to perform normalization. Group name (key) must be unique.
#
# assay_name: Which Seurat assay to use. Seurat assay names are '.' delimited.
#   Currently supported assays names 'Gene.Expression', 'Multiplexing.Capture', 'Peaks', 'Gene.Activity'
#
# norm_method: Method to normalize the group's assay.
#   Currently supported methods: 'log', 'sct', 'clr' or 'lsi'.
normalize:
  split_by: meta_geno
  groups:
    unintegrated_0:
      assay_name: Gene.Expression
      norm_method: sct
    unintegrated_1:
      assay_name: Peaks
      norm_method: lsi
    unintegrated_2:
      assay_name: MACS
      norm_method: lsi
    unintegrated_3:
      assay_name: Gene.Activity
      norm_method: log


# Integrate data sets
# activate: Integrate (transform) count data and/or dimensional reductions/embeddings?
#   Integration rule will create a new Seurat object for each integration performed.
#   All newly created 'integrated' Seurat objects will be concatenated into a list upon rule completion.
#
# memory_MB: Integration of large data may to increase as needed to 5-35 GB. Default R memory is 500 MB. 
#
# atac_integrate_embeddings:
#   If True, integrate low-dimensional cell embeddings (LSI coordinates) across the datasets.
#     Best option for integrating multiple ATAC Peaks data sets.
#   If False, integrate (transform) ATAC Peaks counts matrix across datasets (not LSI coordinates).
#     May over fit. Kept mainly for legacy support.
#
# groups: Each group to perform integration. Group name (key) must be unique. Has to be a column name of your 
# metadata
#
# split_by: Metadata column(s) to generate Seurat list prior to integration
#   Can select from 'feature_type' in samples.tsv, or any column in units.tsv excluding 'sample' and 'unit'.
#
# n_dataset: Integer, The number of datasets to be integrated. 
#
# reference:
#   label: A single element/label from 'split_by' labels. Used as reference Seurat object
#   assay_name: Which assay to use a reference assay for integration?
#     Currently supported assays names 'Gene.Expression', 'Multiplexing.Capture', 'Peaks', 'Gene.Activity'
#
# query:
#   label: One or more labels from 'split_by' labels. Used as query Seurat object
#   assay_name: which assay to use a query assay for integration?
#     Currently supported assays names 'Gene.Expression', 'Multiplexing.Capture', 'Peaks', 'Gene.Activity'
#     
# new_slot_name: Name of the new assay/slot to create in Seurat object during integration. Must be unique.
#   Best option use 'split_by' value and referece 'label' delimited by '.'
#
# norm_method: nNrmalization method to perform on reference and query assays prior to Seurat integration.
#   Currently supported methods: 'log', 'sct', 'clr' or 'lsi'.
#   Suggested methods for integrating only GEX: 'log' or 'sct'.
#   Suggested method for integrating only ATAC: 'lsi'.
#   Suggested method for integrating GEX and ATAC together: 'log'. 
#
# integrate_dims: Range of dimensions to use for integration stap.
#
# umap_dims: Range of dimensions to use for UMAP non-linear reduction after integration.
integrate:
  activate: true
  atac_integrate_embeddings: true
  split_by: meta_geno # this has to match the column name of your metadata indicating datasets for integrati
  groups:
    integrated_0:
      assay_name: Gene.Expression
      norm_method: sct
      integrate_method: CCAIntegration  # RPCAIntegration, HarmonyIntegration, FastMNNIntegration, scVIIntegration
      integrate_dims:
        - 1
        - 30
    integrated_1:
      assay_name: Peaks
      norm_method: lsi
      integrate_method: rlsi
      integrate_dims:
        - 1
        - 30
    # integrated_2:
      # assay_name: MACS
      # norm_method: lsi
      # integrate_dims:
        # - 1
        # - 30
    integrated_3:
      assay_name: Gene.Activity
      norm_method: log
      integrate_method: CCAIntegration
      integrate_dims:
        - 1
        - 30

# Is your input a toy dataset?
# This question is required to adjust the number of neighbors when integrating datasets
dataset_size:
  toydataset: true  # true or false
  toy_k: 10         # size of the number of neighbors when weighting anchors during integration
                    # check `https://satijalab.org/seurat/reference/integrateembeddings`

chooser:
  groups:
    unintegrated_0:
      npcs: 25
    unintegrated_1:
      npcs: 20
    unintegrated_2:
      npcs: 20
    unintegrated_3:
      npcs: 20
    integrated_0:
      npcs: 25
    integrated_1:
      npcs: 20
#   integrated_2:
#     npcs: 25
    integrated_3:
      npcs: 20
  resolutions:
    - 0.6
    - 0.8
  silhouette:
    - silhouette
    - frequency_grouped
    - silhouette_grouped

cluster:
  resolution: 0.6  # Set to null if you're taking advantage of chooser
                     # Go to `weighted_nn` & `resolution` to set the same resolution

# Fix later
# Weighted snn
weighted_nn:
  activate: true
  groups:
    wnn_0:
      neighbor_method: weighted
      input_groups:
        - unintegrated_0 # corresponds to SCT
        - unintegrated_1 # corresponds to Peaks
      reduction:
        - pca
        - lsi
      umap_dims:
        - - 1
          - 25
        - - 1
          - 20
      resolution: 0.6
    wnn_1:
      neighbor_method: weighted
      input_groups:
        - integrated_0 # corresponds to SCT
        - integrated_1 # corresponds to Peaks
      reduction:
        - integrated_pca
        - integrated_lsi
      umap_dims:
        - - 1
          - 25
        - - 1
          - 20
      resolution: 0.6

# differential testing (i.e. diff gene expression, chromatin accessibility, TF motifs)
# can change "cluster_idents" to any metadata column, i.e. "orig.ident", "library_id", "batch_effect", etc
diff_analysis:
  activate: true
  groups:
    unintegrated_0:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: null
      test_use: null
      latent_vars: null
    unintegrated_1:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: 0.2
      test_use: 'LR'
      latent_vars: 'nCount_Peaks'
    unintegrated_2:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: 0.2
      test_use: 'LR'
      latent_vars: 'nCount_MACS'
    integrated_0:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: null
      test_use: null
      latent_vars: null
    integrated_1:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: 0.2
      test_use: 'LR'
      latent_vars: 'nCount_Peaks'
    wnn_0:
      cluster_idents: seurat_clusters
      assay: SCT
      slot: data
      min_pct: null
      test_use: null
      latent_vars: null
    wnn_1:
      cluster_idents: seurat_clusters
      assay: SCT
      slot: data
      min_pct: null
      test_use: null
      latent_vars: null

# Choose guide options:
# build - build initial version of guide.rst from config/template_guide.rst
# render - render guide.html
# etc - do nothing
# NOTE:
# 1. After building the initial guide.rst, you need to manually check input & output file paths
# 2. Set to "etc" if the guide file is not needed
# 3. Set to "etc" if main workflow has not run yet (no 'results' directory)
guide: "etc" # set to "build", "render", or "etc"
