# Sample based data should be included in a samples.tsv file that contains one row per sample (required).
samples: config/atac-config/samples.tsv

# Optionally, barcode suffix/ibrary ID mappings should be included in a aggregates.tsv file.
# This table is required when providing concatenated input matrices
aggregates: config/multiome-config/aggregates.tsv

# Additional assay info should be included in an assays.tsv file that contains one row per assay per sample/rep.
# Only include "DIY" custom count matrices, any "core" matrices/assays are included in 'samples.tsv'.
assays: config/multiome-config/assays.tsv


# Choose how to build your annotation (e.g. EnsDb or GTF)
# NOTE:
# - If you choose "GTF", set ANNO_FILE to the path to your GTF file
# - If your reads have been mapped to a reference where the chromosomes names are unconventional,
#   "EnsDb" is not available due to annotation incompatibility. Use "GTF" instead.
ANNOTATION: "EnsDb"
ANNO_FILE: "path/to/genes.gtf.gz"

# Feature based QC filtering of cells.
# rm_outliers_method: Detect outliers using standard deviation 'sd' or Tukey's interquartile ranger 'iqr'.
#
# meta_labels: Which metadata columns to use for filtering?
#   Can select from 'feature_type' in samples.tsv, or any column in units.tsv excluding 'sample' and 'unit'.
#
# lower: Key:value pairs of metadata column and associated lower limit for cutoff, below which exclude cells.
#   If present, overrides lower limit detected by outlier method.
#   If null, outlier method tries to remove cells automatically
#
# upper: Key:value pairs of metadata column and associated upper limit for cutoff, above which exclude cells.
#   If present, overrides upper limit detected by outlier method.
#   If null, outlier method tries to remove cells automatically
qc:
  remove_outliers: true
  rm_outliers_method: sd
  meta_labels:
    - nCount_Peaks
    - TSS.enrichment
  lower: 
    nCount_Peaks: 1000
    TSS.enrichment: 2
  upper: null


# Determine whether or not to run macs2 (Y or N)
# Do not change the group_fragments_by key unless under special circumstances 
macs2:
  run: "Y"
  group_fragments_by: genome # feature_type


# Normalization and linear reduction
# groups: Each group to perform normalization. Group name (key) must be unique.
#
# assay_name: Which Seurat assay to use. Seurat assay names are '.' delimited.
#   Currently supported assays names 'Gene.Expression', 'Multiplexing.Capture', 'Peaks', 'Gene.Activity'
#
# norm_method: Method to normalize the group's assay.
#   Currently supported methods: 'log', 'sct', 'clr' or 'lsi'.
normalize:
  split_by: meta_geno
  groups:
    unintegrated_1:
      assay_name: Peaks
      norm_method: lsi
    unintegrated_2:
      assay_name: MACS
      norm_method: lsi
    unintegrated_3:
      assay_name: Gene.Activity
      norm_method: log

# Integrate data sets
# activate: Integrate (transform) count data and/or dimensional reductions/embeddings?
#   Integration rule will create a new Seurat object for each integration performed.
#   All newly created 'integrated' Seurat objects will be concatenated into a list upon rule completion.
#
# atac_integrate_embeddings:
#   If True, integrate low-dimensional cell embeddings (LSI coordinates) across the datasets.
#     Best option for integrating multiple ATAC Peaks data sets.
#   If False, integrate (transform) ATAC Peaks counts matrix across datasets (not LSI coordinates).
#     May over fit. Kept mainly for legacy support.
#
# split_by: Metadata column to split layers in Seurat obj for integration
#   Can select from 'meta_*' in samples.tsv or aggregates.tsv
#
# groups: Each group to perform integration. Group name (key) must be unique. Has to be a column name of your 
# metadata
#
# assay_name: assay name saved in Seurat object. This name specifies modality and must be the same as 
#   that specified in the normalize section.
#
# norm_method: Normalization method
#   Currently supported methods: 'log', 'sct', 'clr' or 'lsi'.
#   Suggested methods for integrating only GEX: 'log' or 'sct'.
#   Suggested method for integrating only ATAC: 'lsi'.
#   Suggested method for integrating GEX and ATAC together: 'log'. 
#
# integrate_method: integration algorithm supported in Seurat/Signac workflow.
#   Supported methods for log/sct-normalized modality: CCAIntegration, RPCAIntegration, HarmonyIntegration, FastMNNIntegration, scVIIntegration
#   Supported method for lsi-normalized modality: rlsi
#
# integrate_dims: Range of dimensions to use for integration step.
integrate:
  activate: true
  atac_integrate_embeddings: true
  split_by: meta_geno
  groups:
    integrated_1:
      assay_name: Peaks
      norm_method: lsi
      integrate_method: rlsi
      integrate_dims:
        - 1
        - 30

# Is your input a toy dataset?
# This section is required for small datasets to adjust the number of neighbors when integrating datasets
#
# toydataset: true for toy dataset, false otherwise
#
# toy_k: size of the number of neighbors when weighting anchors during integration
#    This value is passed to weight.k argument in the IntegrateLayers function of Seurat
dataset_size:
  toydataset: false
  toy_k: 10


# ChooseR configuration
#
# groups: modality groups specified in the normalize and integrate sections
#
# npcs: number of reduced dimensions to be considered in chooseR
#
# resolutions: resolutions tested
#
# silhouette: metrics analyzed. Do not change unless under special circumstances.
chooser:
  groups:
    unintegrated_1:
      npcs: 20
    unintegrated_2:
      npcs: 20
    unintegrated_3:
      npcs: 20
    integrated_1:
      npcs: 20
    integrated_2:
      npcs: 20
    integrated_3:
      npcs: 20
  resolutions:
    - 0.6
    - 0.8
    - 1.0
    - 1.2
    - 1.4
    - 1.6
    - 1.8
    - 2.0
  silhouette:
    - silhouette
    - frequency_grouped
    - silhouette_grouped

# Clustering configuration
#
# detection_method: community detection algorithm for unimodal clustering.
#    Supported options are 1 (original Louvain algorithm), 2 (Louvain algorithm with multilevel
#    Louvain algorithm with multilevel refinement), 3 (SLM algorithm), and 
#    Leiden algorithm (requires the leidenalg python).
#
# resolution: null or a float. If null, a chooseR-optimized resolution will be used.
cluster:
  detection_method: 3
  resolution: null


# Weighted nearest neighbor (WNN) used for multimodal analysis
# The WNN is used to compute clusters on a graph where multiple modalities are 
# embedded.
#
# activate: specifies whether or not to run WNN
#
# groups: each group to perform weighted nearest neighbor analysis. Group name 
#   (key) must be unique.
#
# input_groups: two modalities to be integrated, either from the normalize or integrate
#   sections
#
# reduction: reduced dimension used for each unimodal group
#
# umap_dims: range of dimensions to use for UMAP embedding
# 
# resolution: resolution for multimodal clustering
#
# detection_method: community detection algorithm for multimodal clustering.
#   The same algorithms are supported as those in the cluster section
weighted_nn:
  activate: false
  groups:
    wnn_0:
      input_groups:
        - unintegrated_0 # corresponds to SCT
        - unintegrated_1 # corresponds to Peaks
      reduction:
        - pca
        - lsi
      umap_dims:
        - - 1
          - 25
        - - 1
          - 20
      resolution: 0.6
      detection_method: 3
    wnn_1:
      input_groups:
        - integrated_0 # corresponds to SCT
        - integrated_1 # corresponds to Peaks
      reduction:
        - integrated_pca
        - integrated_lsi
      umap_dims:
        - - 1
          - 25
        - - 1
          - 20
      resolution: 0.6
      detection_method: 3

# Differential testing (i.e. diff gene expression, chromatin accessibility, TF motifs)
#
# activate: whether or not to run differential testing
#
# groups: each groups to perform differential testing. group name (key) must be unique.
#
# cluster_idents: metadata column used to compare annotated cells
#   modifiable to any metadata column, e.g. genotype, age, orig.ident, etc
# 
# assay: which assay to use for differential testing. This value is passed to the assay
#   argument of the FindAllMarkers function in Seurat
#
# slot: which slot to pull count data from. This value is passed to the slot argument 
#   of the FindAllMarkers function.
#
# min_pct: minimum proportion of cells expressing a gene to include it in testing.
#   This value is passed to the min.pct argument of the FindAllMarkers function.
# 
# test_use: differential testing method. This value is passed to the test.use 
#   argument of the FindAllMarkers function. If null, the Wilcoxon Rank Sum test is 
#   used by default. Supported methods: wilcox, wilcox_limma, bimod, roc, t,
#   negbinom, poisson, LR, MAST, DESeq2.
# 
# latent_vars: Variable for running LR, negbinom, poisson, or MAST. This value
#   is passed to the latent.vars argument of the FindAllMarkers function.
#
# alpha: False discovery rate (FDR) threshold used to filter significant marker genes
diff_analysis:
  activate: true
  groups:
    unintegrated_1:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: 0.2
      test_use: null
      latent_vars: 'nCount_Peaks'
      alpha: 0.05
    unintegrated_2:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: 0.2
      test_use: null
      latent_vars: 'nCount_MACS'
      alpha: 0.05
    integrated_1:
      cluster_idents: seurat_clusters
      assay: null
      slot: data
      min_pct: 0.2
      test_use: null
      latent_vars: 'nCount_Peaks'
      alpha: 0.05

